[general]
live_config_reload = true

[window]
decorations = "none"
dynamic_padding = false

[window.padding]
x = 0
y = 0

[font]
size = 13
builtin_box_drawing = true

[font.bold]
family = "CodeNewRoman Nerd Font"

[font.bold_italic]
family = "CodeNewRoman Nerd Font"

[font.italic]
family = "CodeNewRoman Nerd Font"

[font.normal]
family = "CodeNewRoman Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
